### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by benbenlaw** [Alex-the-666/Rats#588] opened 2021-02-12 08:35 UTC
[crash-2021-02-12_06.01.50-server.txt](https://github.com/Alex-the-666/Rats/files/5970508/crash-2021-02-12_06.01.50-server.txt)

**Comment by mdedmon** [comment] 2021-02-13 04:57
We're getting this same crash on a regular basis, since updating to 7.1.1 - We're using it as part of the direwolf 1.16.1 update.

[crash-2021-02-13_04.48.36-server.txt](https://github.com/Alex-the-666/Rats/files/5975182/crash-2021-02-13_04.48.36-server.txt)
[crash-2021-02-13_04.30.25-server.txt](https://github.com/Alex-the-666/Rats/files/5975183/crash-2021-02-13_04.30.25-server.txt)
[crash-2021-02-11_01.04.07-server.txt](https://github.com/Alex-the-666/Rats/files/5975184/crash-2021-02-11_01.04.07-server.txt)
[crash-2021-02-13_02.55.35-server.txt](https://github.com/Alex-the-666/Rats/files/5975185/crash-2021-02-13_02.55.35-server.txt)
[crash-2021-02-12_06.01.50-server.txt](https://github.com/Alex-the-666/Rats/files/5975186/crash-2021-02-12_06.01.50-server.txt)

**Comment by ktole1999** [comment] 2021-02-13 14:39
confirmed. seems random but same crash.

**Comment by zlainsama** [comment] 2021-02-14 06:53
@benbenlaw @mdedmon @ktole1999 
Do these class not found exception only happen after at least one server restart?
Are these rats with those upgrades in spawn chunks? or in a force-loaded chunk?
If in a force-loaded chunk, which mod is loading those chunks?

**Comment by benbenlaw** [comment] 2021-02-14 08:26
Yes it jappened aftwr a server restart
Force loaded i think
Ftbchunks

**Comment by mdedmon** [comment] 2021-02-14 11:26
It has happened after a restart. We were trying to troubleshoot it and it seems they may have been in chunk loaded areas. I believe it’s the FTB ?? chunk loader in direwolf20 1.16.1

**Comment by zlainsama** [comment] 2021-02-14 16:22
@benbenlaw @mdedmon 
Can you try https://github.com/zlainsama/Rats/tree/workaroundfix2 on a local copy of your server?

**Comment by mdedmon** [comment] 2021-02-17 04:28
sorry, not a developer here. does this need to be compiled into a .jar file to place on the local copy and test? If so, I don't have the tools / knowledge to do that.

**Comment by zlainsama** [comment] 2021-02-17 07:37
sorry, here is a compiled jar of that: https://github.com/zlainsama/Rats/releases/tag/7.1.1-workaroundfix2
~~I will delete it after done testing.~~ Deleted

**Comment by Chris3606** [comment] 2021-03-16 13:16
@zlainsama In case you never got a response on this; I'm getting very similar crashes under the same conditions (random loaded chunks using ftbchunks on server restart, using the direwolf20 pack).  I'll see if I can give this a try in the next couple days.

**Comment by Chris3606** [comment] 2021-03-17 23:46
Well, my first attempt failed rather spectacularly. More NoClassDefFound exceptions, that appear to be related to Rats pathfinding, and it appeared to be an infinite loop of some sort, so it never stopped spewing errors and didn't write a crash log.  I pulled the latest.log of that run though, which shows the tracebacks it gave before I terminated it:
[2021-03-17-1.log](https://github.com/Alex-the-666/Rats/files/6160389/2021-03-17-1.log)

That only happened the first time I restarted the world, out of 3 attempts.

I am a developer but have no experience in Minecraft modding, and very minimal experience in Java; nonetheless, happy to be of help in troubleshooting and such if I can.

**Comment by zlainsama** [comment] 2021-03-18 07:29
@Chris3606 Can you try it with Chisels & Bits disabled? (modid: chiselsandbits)

**Comment by Chris3606** [comment] 2021-03-19 22:38
@zlainsama Seems to start cleanly without Chisel & Bits, oddly enough.  Tried it a few times, no error on start without it.

For reference, this save-game _with_ chisel crashes fairly consistently.

**Comment by mdedmon** [comment] 2021-04-08 18:35
Hi,
I've been running the workaround version of this mod and it is still crashing. Here are the latest log entries.

[08Apr2021 18:30:22.400] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 0d8afc00-3f5a-4207-9a37-b039904af801
[08Apr2021 18:30:22.404] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap.computeIfAbsent(HashMap.java:1134) ~[?:?]
	at net.minecraft.entity.ai.attributes.AttributeModifierManager.func_233779_a_(SourceFile:48) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_110148_a(LivingEntity.java:1725) ~[?:?]
	at com.github.alexthe666.rats.server.entity.EntityRat.onUpgradeChanged(EntityRat.java:3053) ~[rats:7.1.1]
	at com.github.alexthe666.rats.server.entity.EntityRat.func_70636_d(EntityRat.java:1017) ~[rats:7.1.1]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 5 more

**Comment by mdedmon** [comment] 2021-04-08 19:25
I just noticed this in the log - I had it open while on the server.  Maybe this helps?

[19:06:43] [Thread-16/WARN] [co.pe.co.Performant/]: Error during entity move:
java.util.ConcurrentModificationException: null
	at java.util.HashMap.computeIfAbsent(HashMap.java:1134) ~[?:?] {}
	at net.minecraft.entity.ai.attributes.AttributeModifierManager.func_233779_a_(SourceFile:48) ~[?:?] {re:classloading,xf:fml:astralsorcery:add_player_field}
	at net.minecraft.entity.LivingEntity.func_110148_a(LivingEntity.java:1725) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:set_player_field,xf:fml:astralsorcery:water_movement_slowdown_prevention,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:kubejs-common.mixins.json:LivingEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_213352_e(LivingEntity.java:1900) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:set_player_field,xf:fml:astralsorcery:water_movement_slowdown_prevention,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:kubejs-common.mixins.json:LivingEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.github.alexthe666.rats.server.entity.EntityRat.func_213352_e(EntityRat.java:2060) ~[rats:7.1.1] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.callTravel(LivingEntity.java:3476) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:set_player_field,xf:fml:astralsorcery:water_movement_slowdown_prevention,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:kubejs-common.mixins.json:LivingEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.performant.coremod.entity.threading.MoveThread.run(MoveThread.java:46) [performant:1.16.2-4-3.26m] {re:mixin,re:classloading}

Note: there was no crash - this just popped up.

**Comment by mdedmon** [comment] 2021-04-23 21:20
Any updates on this one? Server is crashing regularly - I think I'll remove the rats mod from the pack until it's fixed.

**Comment by Chris3606** [comment] 2021-04-23 21:30
For my case, I just installed [ChickenChunks](https://www.curseforge.com/minecraft/mc-mods/chickenchunks) and used that for chunk loading instead of FTB chunks, and it seemed to alleviate the problem, although admittedly my sample size isn't huge.

In my case FTB chunks was interacting badly with Refined Storage and causing problems in the DW pack as well, so it made sense for me to switch because it solved that problem as well.

**Comment by GizmoTheMoonPig** [comment] 2022-12-28 06:01
NoSuchMethodError and ClassDefNotFound errors are something I havent been able to reproduce. These methods should exist, especially when it comes to AI tasks, so theres definitely something else going on here. Closing as this is something I cant exactly deal with without more context

**Closed as completed by GizmoTheMoonPig** 2022-12-28 06:01 UTC
