### ISSUE TITLE
Doesn't Work with enderite mod

### ISSUE THREAD

**Issue by FloppyTheWhale** [Alex-the-666/Rats#680] opened 2021-04-16 00:34 UTC
I get an error saying 
"Rats (rats) has failed to load correctly
java.lang.ExceptionInInitializerError: null"

After doing some testing, I learned that with this problem occurs with the enderite mod installed. 
[crash-2021-04-15_20.30.15-fml.txt](https://github.com/Alex-the-666/Rats/files/6321739/crash-2021-04-15_20.30.15-fml.txt)
Update: I am kinda new to modding but found the registry error with the bow, is there anything I can do without uninstalling the enderite mod to get rid of the bow?

**Comment by GizmoTheMoonPig** [comment] 2022-12-28 03:42
duplicate of #404

**Closed as completed by GizmoTheMoonPig** 2022-12-28 03:42 UTC
