### ISSUE TITLE
Conflict with Enderite mod? "java.lang.NullPointerException: Registry Object not present"

### ISSUE THREAD

**Issue by CPSRYAN** [Alex-the-666/Rats#598] opened 2021-02-16 11:54 UTC
On loading up, the launcher crashes with the error above, appears to be a conflict between the mods somehow. Likely an issue with enderite mod.
[Enderite mod](https://www.curseforge.com/minecraft/mc-mods/enderite-mod-for-forge)
[Enderite issue](https://github.com/Nic4Las/Minecraft-Enderite-Mod/issues/26)
[Reddit post (In case it helps)](https://www.reddit.com/r/FeedTheBeastCrashes/comments/ll2083/registry_object_not_present_conflict_with/)
[Log file](https://pastebin.ubuntu.com/p/Y2c3TW2Jf5/)
Forge version is 35.1.37
Minecraft version is 1.16.5
Edit: Should probably mention that by removing/disabling either mod then the pack works

**Comment by GizmoTheMoonPig** [comment] 2022-12-28 03:43
duplicate of #404

**Closed as completed by GizmoTheMoonPig** 2022-12-28 03:43 UTC
