### ISSUE TITLE
Rats teleport out of cage when I walk away

### ISSUE THREAD

**Issue by CircusSeal** [Alex-the-666/Rats#807] opened 2023-07-05 16:01 UTC
In Minecraft 1.16.5, I placed rats in a large cage, but when I walked away, they teleported to follow me. I tried changing their command to Wander and putting them back in, but the same thing happened.

**Comment by GizmoTheMoonPig** [comment] 2023-09-24 15:16
Yeah, rats won't stay in their cages if set to the follow me command, as like other pets, theyll teleport to you if you get too far. They shouldnt be teleporting when in wander mode though. Are you sure you set them all to wander? You can use a rat flute to easily change their command. You can guarantee they wont teleport by telling them all to sit.
Gonna close this as I cant reproduce it in later versions of the mod, and 1.16 isnt supported anymore.

**Closed as completed by GizmoTheMoonPig** 2023-09-24 15:16 UTC
