### ISSUE TITLE
Rats AI Using a Significant Amount of Server Resources

### ISSUE THREAD

**Issue by Darkosto** [Alex-the-666/Rats#127] opened 2019-11-15 21:10 UTC
Hello!

We've been using the Rats mod in the Crackpack 3 modpack and have been really enjoying it. Unfortunately, Rats are taking up a significant amount of server time when untamed but that server timing goes up much higher when tamed and given a job like chopping trees and picking up the dropped items. Is there anything you'd be able to do to help alleviate some of these server issues? I can share .nps profiles from today's server testing and provide any more information if needed.

MC: 1.12.2
Forge: 14.23.5.2847
Rats: 3.2.0-1.12.2

Thanks for your help! If necessary I am livestreaming the making and playing of the modpack: twitch.tv/darkosto This might help if you need testers 

[ServerProfilesCrackpack3.zip](https://github.com/Alex-the-666/Rats/files/3853149/ServerProfilesCrackpack3.zip)

**Comment by Alex-the-666** [comment] 2019-11-15 22:55
i am unable to open .nps files, do you have text or html links?

**Comment by Funwayguy** [comment] 2019-11-15 23:20
There appears to be a particular call in the RatAIHarvestTrees that is particularly slow and being called every tick:

![image](https://user-images.githubusercontent.com/6048596/68982237-effe1200-0851-11ea-89a5-84c93804c5b1.png)

https://github.com/Alex-the-666/Rats/blob/master/src/main/java/com/github/alexthe666/rats/server/entity/ai/RatAIHarvestTrees.java#L41

`CalmDownZombieGuy` is trying to throttle it somewhat

**Comment by Alex-the-666** [comment] 2019-11-15 23:21
ooooh. thats intresting. did not suspect the lumberjacks to cause this

**Comment by Alex-the-666** [comment] 2019-11-15 23:49
fixed. down from 8.3% to 0.6%

**Comment by Alex-the-666** [comment] 2019-11-15 23:50
Any other things causing lags?

**Comment by Funwayguy** [comment] 2019-11-16 01:23
Currently looking into something do with the wandering AI and path navigation. Either it's running far more often than it should (obstructed by some other behaviour maybe) and/or it's loading chunks really far away from itself. This is the particular call stack I'm worried about:

![image](https://user-images.githubusercontent.com/6048596/68985613-78d17980-0863-11ea-9680-0cc7656fdcdb.png)

**Comment by Funwayguy** [comment] 2019-11-16 02:39
I may have tracked down the cause. Wandering AI keeps trying to pathfind then has its path cancelled which causes it to be fired again next tick to try again.

This may be one such location where this happens but I can't be entirely sure if its this or another AI interrupting wander with its own pathing demands:
https://github.com/Alex-the-666/Rats/blob/master/src/main/java/com/github/alexthe666/rats/server/entity/EntityRat.java#L1508

Otherwise it might be worthwhile to add a quick check to your navigator for unloaded chunks if possible.

**Comment by Alex-the-666** [comment] 2019-11-16 02:41
That only happens when diggingPos != null, which is when a rat digs a hole, which they only do under specific circumstances.

**Comment by Funwayguy** [comment] 2019-11-16 03:08
In that case I'll look into the other running AIs. Could be something wrong with mutex bit flags

**Comment by Alex-the-666** [comment] 2019-11-21 05:50
fixed in 3.2.2

**Closed by Alex-the-666** 2019-11-21 05:50 UTC
