### ISSUE TITLE
rats v7.0.4 server crash on entering world

### ISSUE THREAD

**Issue by boneskull** [Alex-the-666/Rats#521] opened 2021-01-10 18:51 UTC
I upgraded from v7.0.3 to v7.0.4 due to the server pathfinding issue, but now I'm consistently crashing on world load (immediately after entering world).  I get a whole lot of stuff like this (`NoClassDefFoundError`s) in `latest.log`:

```
[10:43:39] [Server thread/ERROR]: Catching
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/github/alexthe666/rats/server/pathfinding/pathjobs/AbstractPathJob$SurfaceType
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_275]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_275]
	at com.github.alexthe666.rats.server.pathfinding.RatAdvancedPathNavigate.processCompletedCalculationResult(RatAdvancedPathNavigate.java:324) ~[rats:7.0.4-1.16.3]
	at com.github.alexthe666.rats.server.pathfinding.RatAdvancedPathNavigate.func_75501_e(RatAdvancedPathNavigate.java:148) ~[rats:7.0.4-1.16.3]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:685) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?]
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?]
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:51) ~[?:?]
	at com.github.alexthe666.rats.server.entity.EntityRat.func_70636_d(EntityRat.java:986) ~[rats:7.0.4-1.16.3]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.NoClassDefFoundError: com/github/alexthe666/rats/server/pathfinding/pathjobs/AbstractPathJob$SurfaceType
	at com.github.alexthe666.rats.server.pathfinding.pathjobs.AbstractPathJob.isWalkableSurface(AbstractPathJob.java:1153) ~[rats:7.0.4-1.16.3]
	at com.github.alexthe666.rats.server.pathfinding.pathjobs.AbstractPathJob.getGroundHeight(AbstractPathJob.java:834) ~[rats:7.0.4-1.16.3]
	at com.github.alexthe666.rats.server.pathfinding.pathjobs.PathJobMoveToLocation.search(PathJobMoveToLocation.java:57) ~[rats:7.0.4-1.16.3]
	at com.github.alexthe666.rats.server.pathfinding.pathjobs.AbstractPathJob.call(AbstractPathJob.java:392) ~[rats:7.0.4-1.16.3]
	at com.github.alexthe666.rats.server.pathfinding.pathjobs.AbstractPathJob.call(AbstractPathJob.java:39) ~[rats:7.0.4-1.16.3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_275]
```

Here's a [**crash Log**](https://gist.github.com/boneskull/1695037e44dbc9f60335ed5cc8688259)

I have a few rats hanging out wearing various hats.  The above crash also happens referencing the Farmer Hat; which one I get seems random.

MC version: 1.16.4
Forge version: 35.1.29

May be related to AllTheMods/ATM-6#755 or #514

**Comment by AlexModGuy** [comment] 2021-01-11 00:27
Very strange issue, not sure why it seems to be compiling incompletely with random classes missing.

**Comment by ninjabunny66** [comment] 2021-01-12 02:36
Here are three additional crash reports, the model failing to load for me is the archaeologist's hat
https://pastebin.com/f33pw5U2
https://pastebin.com/4JWb3tJa
https://pastebin.com/nKUFm5h1

**Comment by boneskull** [comment] 2021-01-12 20:19
I have even more if you want them. 😄 

I wonder if the release artifact was corrupted somehow.  Is it possible to generate a fresh one that we could try out?

**Comment by jacquesco07** [comment] 2021-01-20 22:13
Same thing happened to me, except with a Santa Hat. 

Additional crash report here:
[crash-2021-01-20_14.11.28-client.txt](https://github.com/Alex-the-666/Rats/files/5845594/crash-2021-01-20_14.11.28-client.txt)

**Comment by GizmoTheMoonPig** [comment] 2022-12-28 05:38
NoSuchMethodError and ClassDefNotFound errors are something I havent been able to reproduce. These methods should exist, especially when it comes to AI tasks, so theres definitely something else going on here. Closing as this is something I cant exactly deal with without more context

**Closed as completed by GizmoTheMoonPig** 2022-12-28 05:38 UTC
