### ISSUE TITLE
Loading error when initiating breeding process.

### ISSUE THREAD

**Issue by Tomceptor** [Alex-the-666/Rats#250] opened 2020-04-24 13:12 UTC
After the process of breeding starts and the game crashes. You cannot spawn in again. Therefore a world becomes useless. This happened in the newest built of the mod for the version 1.15.2

I attached the crash report

[crash-2020-04-24_14.54.34-client.txt](https://github.com/Alex-the-666/Rats/files/4529029/crash-2020-04-24_14.54.34-client.txt)

**Comment by Partonetrain** [comment] 2020-04-24 16:32
Looks to be a duplicate of https://github.com/Alex-the-666/Rats/issues/248, will be fixed in next version

**Closed** 2020-04-24 19:26 UTC
