### ISSUE TITLE
Minecraft with Rats crashes during loading

### ISSUE THREAD

**Issue by Edison12300** [Alex-the-666/Rats#633] opened 2021-02-27 15:40 UTC
It shows this has failed to load correctly java.lang.ExceptionInItializerError:null.
![螢幕擷取畫面 2021-02-27 233929](https://user-images.githubusercontent.com/71360570/109392076-0ea7ef80-7955-11eb-8a83-1be8daca22e4.png)
Here's the crash report.
[crash-2021-02-27_23.34.54-fml.txt](https://github.com/Alex-the-666/Rats/files/6054746/crash-2021-02-27_23.34.54-fml.txt)

**Comment by GizmoTheMoonPig** [comment] 2022-12-28 06:07
duplicate of #404

**Closed as completed by GizmoTheMoonPig** 2022-12-28 06:07 UTC
