### ISSUE TITLE
Rats produce infinite trash

### ISSUE THREAD

**Issue by irkedIsaac** [Alex-the-666/Rats#450] opened 2020-10-24 17:06 UTC
Version:  7.0.0-1.16.3

Instructing a rat to place items in the trash can will cause them to produce infinite trash, even if they have nothing to transfer (they don't seem to consume items when you give it to them as well)

**Comment by GizmoTheMoonPig** [comment] 2022-12-28 05:27
duplicate of #429

**Closed as completed by GizmoTheMoonPig** 2022-12-28 05:27 UTC
Labels: high priority
