### ISSUE TITLE
1.14 Freeze during world loading

### ISSUE THREAD

**Issue by supito17** [Alex-the-666/Rats#161] opened 2020-01-18 13:43 UTC
rats 4.0.0
citadel 1.3.0
forge 28.1.109 & 28.1.115

my game freeze at 100% on the loading world screen
i tried on an existing world or creating a new one and also 2 different modpack and 2 forge versions.
Game start well with citadel alone.

This is the end of my logs :

[18Jan2020 09:38:51.165] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Preparing start region for dimension minecraft:overworld
[18janv.2020 09:38:51.725] [Client thread/INFO] [net.minecraft.world.chunk.listener.LoggingChunkStatusListener/]: Preparing spawn area: 0%
[18janv.2020 09:38:51.727] [Client thread/INFO] [net.minecraft.world.chunk.listener.LoggingChunkStatusListener/]: Preparing spawn area: 0%
[18janv.2020 09:38:52.843] [Client thread/INFO] [net.minecraft.world.chunk.listener.LoggingChunkStatusListener/]: Preparing spawn area: 83%
[18janv.2020 09:38:52.843] [Client thread/INFO] [net.minecraft.world.chunk.listener.LoggingChunkStatusListener/]: Preparing spawn area: 83%
[18janv.2020 09:38:53.192] [Client thread/INFO] [net.minecraft.world.chunk.listener.LoggingChunkStatusListener/]: Preparing spawn area: 96%
[18janv.2020 09:38:53.692] [Client thread/INFO] [net.minecraft.world.chunk.listener.LoggingChunkStatusListener/]: Preparing spawn area: 98%

**Comment by thornss** [comment] 2020-01-19 11:50
same problem, stuck at 97-99%

**Comment by Mey-Ha-Zah** [comment] 2020-01-24 00:23
Same for me, this and Citadel were my only mods.

**Comment by Dracoian** [comment] 2020-02-02 20:43
I can confirm when disabling the mod the server loads, with the mod activated, it will stop at 99%

**Comment by Lhruggles** [comment] 2020-02-03 13:48
Same issue here. Anyone know how to fix?

**Comment by oliverrook** [comment] 2020-02-08 00:05
I too am having this issue. I'm rather disappointed. Was looking forwards to playing this mod.

**Comment by PokeMaserJ** [comment] 2020-02-15 21:02
I was also having this issue, but it seems to be fixed with at least Forge 28.21 not sure if other versions are also fine with Rats 4.0.0

**Comment by PokeMaserJ** [comment] 2020-02-15 21:40
So just found another bug, you sure can create worlds and load them now. But leaving them and rejoining? Nope. Going to make a report

**Comment by Alex-the-666** [comment] 2020-03-08 20:49
should be fixed in 4.0.2

**Closed by Alex-the-666** 2020-03-08 20:49 UTC
