### ISSUE TITLE
Minecraft 1.16.3 - Game Crash - Rat Mining

### ISSUE THREAD

**Issue by Cyd007** [Alex-the-666/Rats#438] opened 2020-10-08 23:57 UTC
The game crashes as followed:

* A rat is equipped with either a Rat Upgrade: Miner or  Rat Upgrade: Advanced Miner 
* Rat has a single item in its inventory and is returning to a chest to depots the item.
* Rat attempts to break dirt in order to reach chest.
* Game crashes after dirt block is broken. 

<details><summary>Game log here</summary>
<p>
[08Oct2020 16:28:56.571] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:80) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:637) [?:?]
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$5396/941727762.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.IllegalArgumentException: Missing required parameters: [<parameter minecraft:origin>]
	at net.minecraft.loot.LootContext$Builder.func_216022_a(LootContext.java:197) ~[?:?]
	at net.minecraft.block.AbstractBlock.func_220076_a(AbstractBlock.java:211) ~[?:?]
	at com.github.alexthe666.rats.server.entity.RatUtils.destroyBlock(RatUtils.java:637) ~[?:7.0.0-1.16.3]
	at com.github.alexthe666.rats.server.entity.RatUtils.doRatMinerLogic(RatUtils.java:623) ~[?:7.0.0-1.16.3]
	at com.github.alexthe666.rats.server.entity.ai.RatAIDepositInInventory.func_75246_d(RatAIDepositInInventory.java:99) ~[?:7.0.0-1.16.3]
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?]
	at net.minecraft.entity.ai.goal.GoalSelector$$Lambda$5736/1319377559.accept(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_51]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51]
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:88) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:682) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?]
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?]
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:51) ~[?:?]
	at com.github.alexthe666.rats.server.entity.EntityRat.func_70636_d(EntityRat.java:978) ~[?:7.0.0-1.16.3]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:606) ~[?:?]
	at net.minecraft.world.server.ServerWorld$$Lambda$5721/1519628186.accept(Unknown Source) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:399) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) ~[?:?]
	... 6 more
</p>
</details>

Versions use:
Forge: 1.16.3 - 34.1.0
citadel-1.4.0.jar
ratlantis-1.0.0-1.16.3.jar
rats-7.0.0-1.16.3.jar

**Comment by ChillQuil** [comment] 2020-10-20 05:54
Having a problem, when I set my minor rat to mine, the game crashes as soon as he digs up dirt, is there a fix for this?

**Comment by GizmoTheMoonPig** [comment] 2022-12-28 05:31
really need a crash report to troubleshoot this, I cant do much with this little info especially since I cant personally reproduce it

**Comment by GizmoTheMoonPig** [comment] 2022-12-28 05:36
seems to have been fixed by #481

**Closed as completed by GizmoTheMoonPig** 2022-12-28 05:36 UTC
