### ISSUE TITLE
1.20.1 duping the leash when taming a rat

### ISSUE THREAD

**Issue by TemochkaGL** [Alex-the-666/Rats#843] opened 2023-11-09 15:35 UTC
I tied the rats with leashes and tamed them. When the hearts appeared above the rat, the leash fell out, but the rat was still tied up. As a result, instead of two leashes I have 4 of them

**Comment by GizmoTheMoonPig** [comment] 2023-11-09 16:21
duplicate of #840, will be fixed in 8.1.3

**Closed as completed by GizmoTheMoonPig** 2023-11-09 16:21 UTC
